
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r cicd-simple-flask-app/requirements.txt
  build:
    commands:
      - echo "Running tests..."
      - cd cicd-simple-flask-app/
      - echo "Building Docker image..."
      - docker login -u "jayendra0903@gmail.com" -p "Jayendra@2002"
      - docker build -t "jayendraklouder/cicd-flask-app:latest" .
      - docker push "jayendraklouder/cicd-flask-app:latest"
  post_build:
    commands:
      - echo "Build completed successfully!"
  
artifacts:
  files:
  #  - '**/*'
  #base-directory: cicd-simple-flask-app/
    - imagedefinitions.json
